//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emigrantes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emergencias
    {
        public int Id { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Estado { get; set; }
    
        public virtual Emigrante Emigrante { get; set; }
    }
}
