//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emigrantes
{
    using System;
    using System.Collections.Generic;
    
    public partial class emigrantesServicios
    {
        public int Id { get; set; }
        public Nullable<int> IdSolicitud { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public Nullable<System.DateTime> Fecha_solicitud { get; set; }
        public Nullable<System.DateTime> Fecha_Respuesta { get; set; }
        public Nullable<double> Estado_Solicitud { get; set; }
        public string Evaluacion { get; set; }
    
        public virtual Emigrante Emigrante { get; set; }
        public virtual Servicios Servicios { get; set; }
        public virtual tipoSolicitud tipoSolicitud { get; set; }
    }
}
