//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emigrantes.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmigrantesEntities : DbContext
    {
        public EmigrantesEntities()
            : base("name=EmigrantesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emergencias> Emergencias { get; set; }
        public virtual DbSet<Emigrante> Emigrante { get; set; }
        public virtual DbSet<emigrantesServicios> emigrantesServicios { get; set; }
        public virtual DbSet<Entidad> Entidad { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<GruposMigrantes> GruposMigrantes { get; set; }
        public virtual DbSet<migrantesNecesidad> migrantesNecesidad { get; set; }
        public virtual DbSet<Necesidades> Necesidades { get; set; }
        public virtual DbSet<prioridadNecesidad> prioridadNecesidad { get; set; }
        public virtual DbSet<sectorEntidad> sectorEntidad { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<situacionLaboral> situacionLaboral { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipoSolicitud> tipoSolicitud { get; set; }
    }
}
